general:
  input_dir: '..\\..\\data\\test_human_20\\'
  output_dir: '..\\..\\outputs\\'
  summary_stats:
    active: True
  verbose: False

features:
  extract_basic_image_features:
    active: True
    parameters: None

  neural_image_assessment:
    active: False
    parameters: None

  extract_blur_value:
    active: False
    parameters: None

  estimate_noise:
    active: False
    parameters: None

  calculate_contrast_of_brightness:
    active: False
    parameters: None

  calculate_image_clarity:
    active: False
    parameters: None

  calculate_hue_proportions:
    active: False
    parameters: None

  calculate_salient_region_features:
    active: False
    parameters: None

  predict_coco_labels_yolo11:
    active: False
    parameters: None

  predict_imagenet_classes_yolo11:
    active: False
    parameters: None

  get_color_features:
    active: False
    parameters: None

  get_composition_features:
    active: False
    parameters: None

  get_figure_ground_relationship_features:
    active: False
    parameters: None

  visual_complexity:
    active: False
    parameters: None

  detect_objects:
    active: False
    parameters: 
      objects_to_detect:
        - 'person'
        - 'car'
        - 'bicycle'
        - 'motorcycle'
        - 'bus'
        - 'train'

  calculate_aesthetic_scores:
    active: False
    parameters:
      weight_filename: 'weights_mobilenet_aesthetic_0.07.hdf5'
      weight_url: 'https://github.com/idealo/image-quality-assessment/blob/master/models/MobileNet/weights_mobilenet_aesthetic_0.07.hdf5?raw=true'

  get_ocr_text:
    active: False
    parameters:
      windows_path_to_tesseract: 'C:\\Users\\ge53hed\\AppData\\Local\\Tesseract-OCR\\tesseract.exe' 