general:
  input_dir: '..\\..\\data\\test_human_20\\'
  output_dir: '..\\..\\outputs\\'
  summary_stats:
    active: True
  verbose: False
  debug_mode: False
  debug_image_count: 2 # If debug_mode is True, then randomly select debug_image_count images for processing
  multi_processing: 
    active: False
    num_processes: 4

features:
  extract_basic_image_features:
    active: True
    parameters: None

  extract_blur_value:
    active: True
    parameters: None

  estimate_noise:
    active: True
    parameters: None

  calculate_contrast_of_brightness:
    active: True
    parameters: None

  calculate_image_clarity:
    active: True
    parameters: None

  calculate_hue_proportions:
    active: True
    parameters: None

  calculate_salient_region_features:
    active: False
    parameters: None

  predict_coco_labels_yolo11:
    active: True
    parameters: None

  predict_imagenet_classes_yolo11:
    active: True
    parameters: None

  get_color_features:
    active: True
    parameters:
      clarity_threshold: 0.7
      warmHue_threshold_lower: 70
      warmHue_threshold_upper: 160

  get_composition_features:
    active: True
    parameters: None

  get_figure_ground_relationship_features:
    active: True
    parameters: 
      saliency_threshold: 0.5
      canny_edge_low_threshold: 100
      canny_edge_high_threshold: 200

  visual_complexity:
    active: True
    parameters: 
      threshold: 25000
    
  self_similarity:
    active: True
    parameters: None

  detect_objects:
    active: False
    parameters: 
      objects_to_detect:
        - 'object'
        - 'animal'
        - 'human'
        - 'consumer'
        - 'consumer product'

  calculate_aesthetic_scores:
    active: True
    parameters:
      weight_filename: 'weights_mobilenet_aesthetic_0.07.hdf5'
      weight_url: 'https://github.com/idealo/image-quality-assessment/blob/master/models/MobileNet/weights_mobilenet_aesthetic_0.07.hdf5?raw=true'

  get_ocr_text:
    active: True
    parameters:
      windows_path_to_tesseract: 'C:\\Users\\ge53hed\\AppData\\Local\\Tesseract-OCR\\tesseract.exe'
  
  describe_blip:
    active: False
    parameters: 
      processor: 'Salesforce/blip-image-captioning-base'
      model: 'Salesforce/blip-image-captioning-base'

  describe_llm:
    active: False
    parameters: 
      model: 'microsoft/Phi-4-multimodal-instruct'
      max_new_tokens: 1000